import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import Providers from '@/components/providers';
import TopNav from '@/components/navbar/top-nav';

import { auth } from '@/auth';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  // console.log('🚀 ~ session:', session);
  const userId = session?.user?.id || null;

  const profileComplete = session?.user.profileComplete as boolean;

  return (
    // <SessionProvider session={session}>
    <html lang='en'>
      <body className={cn(inter.className)}>
        <Providers userId={userId} profileComplete={profileComplete}>
          <div className='purple-dark text-foreground bg-background h-[100vh]'>
            <TopNav />
            <main className='container mx-auto'>{children}</main>
          </div>
        </Providers>
      </body>
    </html>
    // </SessionProvider>
  );
}
